config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  resources :activities
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "main#index"

  resources :dashboard, only: :index
end

app/models/activity.rb
class Activity < ApplicationRecord
  extend Enumerize
  belongs_to :user

  has_many :questions

  validates :user, presence: :true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/motor/ability.rb
module Motor
  class Ability
    include CanCan::Ability

    def initialize(user, _request)
      can :manage, Activity, { user_id: user.id }
      can :read, Question, { activity: { user_id: user.id } }
      can :manage, User, id: user.id
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:user_id, :theme, :difficulty, :question_quantity, :is_public)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    motor_admin_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activity.html.slim
div id="#{dom_id activity}"
  p
    strong User:
    =< activity.user_id
  p
    strong Theme:
    =< activity.theme
  p
    strong Difficulty:
    =< activity.difficulty
  p
    strong Question quantity:
    =< activity.question_quantity
  p
    strong Is public:
    =< activity.is_public

app/views/activities/_form.html.slim
= form_with(model: activity) do |form|
  - if activity.errors.any?
    div style="color: red"
      h2 = "#{pluralize(activity.errors.count, "error")} prohibited this activity from being saved:"
      ul
        - activity.errors.each do |error|
          li = error.full_message

  div
    = form.label :user_id, style: "display: block"
    = form.text_field :user_id

  div
    = form.label :theme, style: "display: block"
    = form.text_field :theme

  div
    = form.label :difficulty, style: "display: block"
    = form.text_field :difficulty

  div
    = form.label :question_quantity, style: "display: block"
    = form.text_field :question_quantity

  div
    = form.label :is_public, style: "display: block"
    = form.check_box :is_public

  div
    = form.submit

app/views/activities/edit.html.slim
h1 Editing activity

== render "form", activity: @activity

br

div
  => link_to "Show this activity", @activity
  '|
  =< link_to "Back to activities", activities_path

app/views/activities/index.html.slim
p style="color: green" = notice

h1 Activities

#activities
  - @activities.each do |activity|
    == render activity
    p
      = link_to "Show this activity", activity

= link_to "New activity", new_activity_path

app/views/activities/new.html.slim
h1 New activity

== render "form", activity: @activity

br

div
  = link_to "Back to activities", activities_path

app/views/activities/show.html.slim
p style="color: green" = notice

== render @activity

div
  => link_to "Edit this activity", edit_activity_path(@activity)
  '|
  =< link_to "Back to activities", activities_path

  = button_to "Destroy this activity", @activity, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EducativaUfabc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.slim
div[style="width: 100%; height: 100%; padding-top: 211px; padding-bottom: 256px; background: white; flex-direction: column; justify-content: flex-start; align-items: center; gap: 49px; display: inline-flex"]
  div[style="width: 642px; height: 41px; text-align: center; color: black; font-size: 40px; font-family: Montserrat; font-weight: 300; text-transform: uppercase; line-height: 20px; word-wrap: break-word"]
    | Plataforma educacional
  div[style="width: 477px; height: 73px; text-align: center; color: black; font-size: 24px; font-family: Montserrat; font-weight: 300; text-transform: uppercase; line-height: 20px; word-wrap: break-word"]
    | Uma solução para criação de atividades escolares
  div[style="justify-content: flex-start; align-items: flex-start; display: inline-flex"]
  = link_to 'Login', new_user_session_path, style: "color: black"
  = link_to 'Criar conta', new_user_registration_path, style: "color: black"